spring:
  application:
    name: football-service
  datasource:
    url: jdbc:postgresql://localhost:5432/footballService
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      lifecycle-management: start_only
  data:
    redis:
      host: redis
      port: 6379


server:
  port: 4000
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
        secure: false  # Set to true in production with HTTPS'
        name: SESSION
        path: /
      timeout: 30m




API:
  KEY: "b3bb5ddd7a0247ab9e92d17c31c6ff94"

logging:
  level:
    io:
      lettuce:
        core: DEBUG
      org:
        springframework:
          security:
            web:
              authentication: DEBUG
              context: DEBUG
          session: DEBUG
    root: INFO  # Or TRACE for maximum verbosity
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Show SQL query bindings
    com.pm.footballservice: DEBUG  # <-- replace with your own package name

